import {initializeApp} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {getFirestore,collection,doc,getDocs,setDoc,addDoc,serverTimestamp,writeBatch,query,where} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import {firebaseConfig,profiles} from "./config.js";

const fb=initializeApp(firebaseConfig), auth=getAuth(fb), db=getFirestore(fb), root=document.getElementById("app");
let S={user:null,profile:null,challenges:[],attempts:[],route:"home",challenge:null};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const profByEmail=e=>Object.values(profiles).find(p=>p.email.toLowerCase()===(e||"").toLowerCase());
const admin=()=>S.profile?.role==="admin";

const hebrewPassage=`ביום שלישי בבוקר הגיע נועם לבית הספר מוקדם מהרגיל. אבא שלו היה צריך להגיע לעבודה מוקדם, ולכן נועם היה כמעט הראשון בבית הספר.

באותו יום התקיימה תחרות "הממציא הצעיר". מאיה בנתה מכשיר שמזכיר להשקות עציצים, ונועם בנה "מערכת אוטומטית להגנה על כריכים": קופסת אוכל עם פעמון קטן שמצלצל כאשר פותחים אותה.

המחנכת יעל נכנסה לכיתה עם תיק שחור גדול. בתוכו היו המדליות לזוכים ושוברים לחנות הספרים. אחר כך ירדה הכיתה לאולם הספורט. בשעה תשע וחצי עלתה מאיה לכיתה כדי להביא מספריים, וכעבור רגע נשמעה צעקה: "התיק נעלם!"

נועם ומאיה התחילו לחקור. מתחת לשולחן מצאו עטיפת מסטיק, וליד הדלת היו טיפות מים. איציק השרת סיפר שראה מישהו עם כובע אדום. נועם חשד ברועי, שנהג להגיע עם כובע אדום, אבל לרועי היו בערך שלושים עדים לכך שהיה באולם.

לפתע נשמע צלצול קטן: דינג־דינג! נועם זיהה את הפעמון שלו. הם הלכו בעקבות הצליל עד למחסן הציוד ושם מצאו את התיק השחור. משהו זז מאחוריו, מאיה צרחה, ונועם קפץ לאחור ושלושה כדורי סל נפלו עליו. מאחורי התיק יצא חתול אפור.

מאיה פתחה את התיק: המדליות והשוברים היו בפנים. אז נשמע שוב הפעמון מתוך ארגז גדול. נועם פתח אותו וגילה שם את קופסת האוכל שלו. דניאל הופיע והודה שפתח את הקופסה. כשהפעמון צלצל הוא נבהל, לקח אותה למחסן, וכנראה דחף בטעות עגלה שעליה היה התיק.

באותו רגע הגיעה יעל והסבירה שהיא עצמה העבירה קודם את התיק מהשולחן לעגלה, התכוונה לקחת אותו לאולם, אבל שכחה. כולם הבינו שאף אחד לא גנב את התיק.

נועם פתח את קופסת האוכל וגילה שהכריך שלו נעלם. כולם הסתכלו על דניאל. "זו ראיה נסיבתית בלבד," אמר דניאל.

בסופו של דבר מאיה זכתה במקום השני ונועם קיבל פרס יצירתיות. כשהמנהל שאל אם מערכת ההגנה על הכריכים באמת עובדת, נועם ענה: "כן, אבל בגרסה הבאה אני מוסיף אזעקה."`;

const starters=[
{id:"hebrew-unseen-001",title:"תעלומת התיק שנעלם",subject:"Hebrew",language:"he",level:"Grades 6–8",difficulty:"Medium",targetStudents:["amit","maya"],description:"אנסין מצחיק ומותח עם 15 שאלות.",passage:hebrewPassage,questions:[
{id:"q1",type:"mcq",text:"מדוע הגיע נועם לבית הספר מוקדם?",options:["כדי ללמוד למבחן","כי אביו היה צריך להגיע לעבודה מוקדם","כי התחרות התחילה מוקדם","כדי לפגוש את מאיה"],answer:1},
{id:"q2",type:"mcq",text:"מה הייתה ההמצאה של נועם?",options:["מערכת השקיה","מכשיר למציאת תיקים","קופסת אוכל עם פעמון","שעון מעורר"],answer:2},
{id:"q3",type:"mcq",text:"מה היה בתיק השחור?",options:["אוכל","מדליות ושוברים","ציוד ספורט","ספרים"],answer:1},
{id:"q4",type:"mcq",text:"מה היה הרמז הראשון?",options:["כובע אדום","טיפות מים","עטיפת מסטיק","כדור סל"],answer:2},
{id:"q5",type:"mcq",text:"מדוע חשדו ברועי?",options:["הוא הודה","נמצא הכובע שלו","איציק ראה מישהו עם כובע אדום","הוא עזב את בית הספר"],answer:2},
{id:"q6",type:"mcq",text:"מה הוביל את נועם ומאיה למחסן?",options:["החתול","יעל","צליל הפעמון","רועי"],answer:2},
{id:"q7",type:"mcq",text:"מי גנב את התיק?",options:["דניאל","רועי","החתול","אף אחד"],answer:3},
{id:"q8",type:"mcq",text:"מה משמעות דבריו של דניאל: 'זו ראיה נסיבתית בלבד'?",options:["הוא מנסה להצחיק ולהתחמק","הוא כועס","הוא חושב שהתיק אבוד","הוא רוצה להזמין משטרה"],answer:0},
{id:"q9",type:"open",text:"מדוע נועם התלהב מהחקירה?",keywords:["סקרן","תעלומה","בלש","דמיון"],need:1,example:"נועם סקרן ואוהב תעלומות, ולכן נהנה לשחק בלש."},
{id:"q10",type:"open",text:"כיצד הפעמון עזר לפתור את התעלומה?",keywords:["פעמון","צליל","מחסן"],need:2,example:"הפעמון צלצל והוביל אותם למחסן שבו נמצא התיק."},
{id:"q11",type:"open",text:"ציינו שני דברים שגרמו להם לחשוב שמישהו לקח את התיק.",keywords:["נעלם","מסטיק","טיפות","רמז"],need:2,example:"התיק נעלם, והם מצאו עטיפת מסטיק וטיפות מים."},
{id:"q12",type:"open",text:"מדוע החשד ברועי היה שגוי?",keywords:["אולם","עדים","שלושים"],need:1,example:"רועי היה באולם והיו לו עדים רבים."},
{id:"q13",type:"open",text:"מה אפשר ללמוד על דניאל?",keywords:["אוכל","כריך","הומור","מצחיק"],need:2,example:"הוא אוהב אוכל וגם משתמש בהומור כדי להתחמק ממבוכה."},
{id:"q14",type:"open",text:"תנו דוגמה למצב מותח שהפך למצחיק.",keywords:["חתול","כדורי","מחסן"],need:1,example:"הם חשבו שמשהו מסוכן מסתתר, אבל זה היה רק חתול."},
{id:"q15",type:"open",text:"אילו שני שיפורים הייתם מוסיפים למערכת?",keywords:[],need:0,creative:true,example:"למשל אזעקה חזקה יותר ומנעול עם קוד."}
]},
{id:"english-reading-001",title:"The Missing Lunchbox",subject:"English",language:"en",level:"Grades 6–8",difficulty:"Easy",targetStudents:["amit","maya"],description:"A short reading comprehension challenge.",passage:`On Monday morning, Leo arrived at school carrying a bright green lunchbox. At lunchtime, it was gone. Leo and his friend Nora searched the classroom and found three cookie crumbs near the door. The crumbs led toward the art room. Inside, they found the lunchbox on a chair. Mr. Kim, the art teacher, explained that he had mistaken it for a box of clay tools. The sandwich and apple were still inside, but the cookies were missing. Then Peanut, the school hamster, crawled out from behind a cabinet with a chocolate crumb on his nose. Leo laughed. "Mystery solved... mostly."`,questions:[
{id:"q1",type:"mcq",text:"What color was the lunchbox?",options:["Blue","Green","Red","Yellow"],answer:1},
{id:"q2",type:"mcq",text:"What clue did they find?",options:["A note","Cookie crumbs","A pencil","A shoe"],answer:1},
{id:"q3",type:"mcq",text:"Where was the lunchbox?",options:["Library","Gym","Art room","Office"],answer:2},
{id:"q4",type:"mcq",text:"Why did Mr. Kim take it?",options:["He was hungry","He thought it contained clay tools","He hid it","Nora asked him"],answer:1},
{id:"q5",type:"mcq",text:"Who probably ate the cookies?",options:["Leo","Nora","Mr. Kim","Peanut"],answer:3},
{id:"q6",type:"open",text:"Why is the ending funny?",keywords:["hamster","crumb","cookie","nose"],need:1,example:"The hamster has a chocolate crumb on his nose, so he probably ate the cookies."}
]},
{id:"ella-english-001",title:"Colors & Animals",subject:"English",language:"en",level:"Kindergarten",difficulty:"Starter",targetStudents:["ella"],description:"A playful English starter challenge.",passage:"",questions:[
{id:"q1",type:"mcq",text:"Which word means 🐱 ?",options:["cat","dog","sun","book"],answer:0},{id:"q2",type:"mcq",text:"Which word means 🔴 ?",options:["blue","green","red","yellow"],answer:2},{id:"q3",type:"mcq",text:"Which word means 🐶 ?",options:["dog","fish","bird","apple"],answer:0},{id:"q4",type:"mcq",text:"Which word means ☀️ ?",options:["moon","sun","tree","car"],answer:1}
]},
{id:"ella-hebrew-001",title:"אותיות ומילים",subject:"Hebrew",language:"he",level:"Kindergarten",difficulty:"Starter",targetStudents:["ella"],description:"תרגול קצר וחזותי.",passage:"",questions:[
{id:"q1",type:"mcq",text:"איזו מילה מתאימה לתמונה 🐶?",options:["כלב","חתול","בית","שמש"],answer:0},{id:"q2",type:"mcq",text:"באיזו אות מתחילה המילה 'אבא'?",options:["א","ב","ג","ד"],answer:0},{id:"q3",type:"mcq",text:"איזו מילה מתאימה לתמונה ☀️?",options:["ים","שמש","ספר","עץ"],answer:1},{id:"q4",type:"mcq",text:"באיזו אות מתחילה המילה 'בית'?",options:["א","ב","ל","מ"],answer:1}
]}
];

function shell(x){return `<div class="${S.profile?.id==='ella'?'ella':''}"><header class="top"><div class="brand"><div class="logo">BP</div><span>BrightPath Kids</span></div><div>${S.profile?`<span class="badge">${S.profile.emoji} ${esc(S.profile.name)}</span>`:''} ${S.user?`<button class="btn" data-home>Home</button> <button class="btn danger" data-out>Log out</button>`:''}</div></header>${x}</div>`}
function login(){return `<div class="login"><div class="loginbox"><div class="logo" style="margin:auto">BP</div><h1>BrightPath Kids</h1><p class="muted">Choose a profile and enter the password.</p><div class="profiles">${Object.values(profiles).map((p,i)=>`<button class="profile ${i===0?'active':''}" data-prof="${p.id}"><div class="avatar">${p.emoji}</div><b>${esc(p.name)}</b><div class="muted">${esc(p.grade||'Parent / Admin')}</div></button>`).join('')}</div><form id="loginForm"><input type="hidden" id="pid" value="admin"><div class="field"><label>Password</label><input id="pass" type="password" required></div><div id="loginMsg"></div><button class="btn primary" style="width:100%">Log in</button></form></div></div>`}
function student(){const p=S.profile, mine=S.challenges.filter(c=>(c.targetStudents||[]).includes(p.id)), a=S.attempts.filter(x=>x.studentId===p.id), best=a.length?Math.max(...a.map(x=>x.percent||0)):0, avg=a.length?Math.round(a.reduce((s,x)=>s+(x.percent||0),0)/a.length):0;return shell(`<main class="wrap"><section class="hero"><h1>Hi ${esc(p.name.split(' ')[0])}! ${p.id==='ella'?'🌈':'👋'}</h1><p>${p.id==='ella'?'Pick a fun activity and earn stars!':'Choose a challenge and watch your progress grow.'}</p></section><div class="stats"><div class="card stat"><strong>${mine.length}</strong><span>Challenges</span></div><div class="card stat"><strong>${a.length}</strong><span>Attempts</span></div><div class="card stat"><strong>${avg}%</strong><span>Average</span></div><div class="card stat"><strong>${best}%</strong><span>Best</span></div></div><div class="section"><h2>Challenges</h2></div><div class="grid">${mine.length?mine.map(c=>challengeCard(c,a)).join(''):`<div class="notice">No challenges yet. Ask Admin to seed starter challenges.</div>`}</div></main>`)}
function challengeCard(c,a){const ca=a.filter(x=>x.challengeId===c.id), best=ca.length?Math.max(...ca.map(x=>x.percent||0)):null;return `<div class="card challenge ${c.language==='he'?'rtl':''}"><div><h3>${esc(c.title)}</h3><div class="muted">${esc(c.description||'')}</div><div><span class="badge">${esc(c.subject)}</span><span class="badge">${esc(c.level)}</span>${best!==null?`<span class="badge">Best ${best}%</span>`:''}</div></div><button class="btn primary" data-open="${c.id}">${ca.length?'Try again':'Start'}</button></div>`}
function challengeView(id){const c=S.challenges.find(x=>x.id===id);if(!c)return shell(`<main class="wrap"><div class="notice error">Challenge not found.</div></main>`);return shell(`<main class="wrap ${c.language==='he'?'rtl':''}"><div class="section"><h2>${esc(c.title)}</h2><p class="muted">${esc(c.description||'')}</p></div><form id="challengeForm" data-id="${c.id}" class="challengepage"><section class="card">${(c.questions||[]).map((q,i)=>qhtml(q,i,c.language)).join('')}<div id="result"></div><button class="btn good" style="margin-top:15px">${c.language==='he'?'בדיקת תשובות':'Check answers'}</button></section><aside class="card reading"><h3>${c.language==='he'?'קטע הקריאה':'Reading'}</h3>${c.passage?`<div class="passage">${esc(c.passage)}</div>`:`<div class="notice">${c.language==='he'?'אין קטע קריאה':'No reading passage'}</div>`}</aside></form></main>`)}
function qhtml(q,i,lang){return `<div class="q"><h4>${i+1}. ${esc(q.text)}</h4>${q.type==='mcq'?(q.options||[]).map((o,j)=>`<label class="opt"><input type="radio" name="${q.id}" value="${j}"> ${esc(o)}</label>`).join(''):`<textarea class="answer" name="${q.id}" placeholder="${lang==='he'?'כתבו כאן...':'Type your answer...'}"></textarea>`}<div class="fb" id="fb-${q.id}"></div></div>`}
function adminView(){const students=['amit','maya','ella'].map(id=>profiles[id]);return shell(`<main class="wrap"><section class="hero"><h1>Admin Dashboard 📊</h1><p>Monitor each student separately and manage learning content.</p></section><div class="section"><h2>Student progress</h2></div><div class="grid g3">${students.map(p=>{const a=S.attempts.filter(x=>x.studentId===p.id),avg=a.length?Math.round(a.reduce((s,x)=>s+(x.percent||0),0)/a.length):0,best=a.length?Math.max(...a.map(x=>x.percent||0)):0;return `<div class="card"><div class="avatar">${p.emoji}</div><h3>${p.name}</h3><div class="muted">${p.grade} · Age ${p.age}</div><p><b>${avg}%</b> average · <b>${best}%</b> best · ${a.length} attempts</p></div>`}).join('')}</div><div class="section"><h2>Content</h2></div><div class="grid g2"><div class="card"><h3>Starter challenges</h3><p>Publish the prepared exercises into Firestore.</p><button class="btn primary" id="seed">Seed / refresh starter challenges</button><div id="seedMsg"></div></div><div class="card"><h3>Ella</h3><p>Ella's profile and starter activities are ready. Create <b>ella@itrna.com</b> in Firebase Authentication when you want her to log in.</p></div></div><div class="section"><h2>Recent attempts</h2></div>${attemptTable()}</main>`)}
function attemptTable(){if(!S.attempts.length)return `<div class="notice">No attempts yet.</div>`;return `<div class="card table"><table><thead><tr><th>Student</th><th>Challenge</th><th>Subject</th><th>Score</th><th>%</th></tr></thead><tbody>${S.attempts.map(a=>`<tr><td>${esc(a.studentName||a.studentId)}</td><td>${esc(a.challengeTitle||a.challengeId)}</td><td>${esc(a.subject||'')}</td><td>${a.score}/${a.total}</td><td><b>${a.percent}%</b></td></tr>`).join('')}</tbody></table></div>`}
function norm(t){return (t||'').toLowerCase().normalize('NFKD').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim()}
function grade(q,v){if(q.type==='mcq')return Number(v)===Number(q.answer);const t=norm(v);if(q.creative)return t.length>=8;const kws=(q.keywords||[]).map(norm),hits=kws.filter(k=>k&&t.includes(k)).length;return t.length>2&&hits>=(q.need??1)}
async function submit(form){const c=S.challenges.find(x=>x.id===form.dataset.id),fd=new FormData(form);let score=0;for(const q of c.questions){const v=String(fd.get(q.id)||''),ok=grade(q,v);if(ok)score++;const el=document.getElementById('fb-'+q.id);el.innerHTML=`<span class="${ok?'correct':'wrong'}">${ok?'✓ Correct':'✗ Review this answer'}</span>${!ok&&q.example?`<div class="muted">Example: ${esc(q.example)}</div>`:''}`;}const total=c.questions.length,percent=Math.round(score/total*100);document.getElementById('result').innerHTML=`<div class="notice success"><div class="score">${percent}%</div><b>${score}/${total}</b><p>${percent>=80?'Excellent work! 🌟':percent>=60?'Nice work — keep practising! 💪':'Good start — review and try again. 🌱'}</p></div>`;await addDoc(collection(db,'attempts'),{uid:S.user.uid,studentId:S.profile.id,studentName:S.profile.name,challengeId:c.id,challengeTitle:c.title,subject:c.subject,score,total,percent,createdAt:serverTimestamp()});await loadAttempts()}
async function loadChallenges(){const s=await getDocs(collection(db,'challenges'));S.challenges=s.docs.map(d=>({id:d.id,...d.data()}))}
async function loadAttempts(){if(admin()){const s=await getDocs(collection(db,'attempts'));S.attempts=s.docs.map(d=>({id:d.id,...d.data()}))}else{const s=await getDocs(query(collection(db,'attempts'),where('uid','==',S.user.uid)));S.attempts=s.docs.map(d=>({id:d.id,...d.data()}))}}
async function seed(){const m=document.getElementById('seedMsg');try{const b=writeBatch(db);for(const c of starters)b.set(doc(db,'challenges',c.id),c,{merge:true});await b.commit();await loadChallenges();m.innerHTML=`<div class="notice success">${starters.length} starter challenges are ready.</div>`}catch(e){m.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}}
function route(){const h=(location.hash||'#home').slice(1).split('/');S.route=h[0];S.challenge=h[1]||null;render()}
function render(){if(!S.user){root.innerHTML=login();bind();return}if(S.route==='challenge'&&S.challenge)root.innerHTML=challengeView(S.challenge);else root.innerHTML=admin()?adminView():student();bind()}
function bind(){document.querySelectorAll('[data-prof]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-prof]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('pid').value=b.dataset.prof});const f=document.getElementById('loginForm');if(f)f.onsubmit=async e=>{e.preventDefault();const p=profiles[document.getElementById('pid').value],m=document.getElementById('loginMsg');try{m.innerHTML='<div class="notice">Signing in…</div>';await signInWithEmailAndPassword(auth,p.email,document.getElementById('pass').value)}catch(err){m.innerHTML=`<div class="notice error">${p.id==='ella'?"Ella's Firebase account may not exist yet. ":''}${esc(err.message)}</div>`}};document.querySelectorAll('[data-out]').forEach(b=>b.onclick=()=>signOut(auth));document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>location.hash='home');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>location.hash='challenge/'+b.dataset.open);const cf=document.getElementById('challengeForm');if(cf)cf.onsubmit=e=>{e.preventDefault();submit(cf)};const s=document.getElementById('seed');if(s)s.onclick=seed}
window.addEventListener('hashchange',route);
onAuthStateChanged(auth,async u=>{S.user=u;S.profile=u?profByEmail(u.email):null;if(u){try{await loadChallenges();await loadAttempts()}catch(e){console.error(e)}}else{S.challenges=[];S.attempts=[]}route()});
